SELECT TOP (1000) [Id]
      ,[CustomerName]
      ,[CustomerAddress]
  FROM [Outbox.StoreFront].[dbo].[Orders]

SELECT TOP (1000) [Id]
      ,[OrderId]
      ,[InventoryRecordId]
      ,[Count]
  FROM [Outbox.StoreFront].[dbo].[OrderItems]

SELECT TOP (1000) [Id]
      ,[MessageType]
      ,[EventName]
      ,[Payload]
      ,[CreatedAt]
      ,[Processed]
      ,[ProcessedAt]
  FROM [Outbox.StoreFront].[dbo].[EventMessages]

SELECT TOP (1000) [Id]
      ,[Name]
      ,[AvailableCount]
      ,[OnHoldCount]
      ,[SoldCount]
  FROM [Outbox.StoreFront].[dbo].[Inventory]
